services:
  psql_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  golang-server:
    build:
      context: https://github.com/MikelGV/SpecialtyCoffeeCrawler.git
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - psql_db
  roast-nomads-client:
    build:
      context: https://github.com/MikelGV/roast-nomads-client.git
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

volumes:
  psql_volume:

networks:
  my_network:
    driver: bridge
